blocklists:
  - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
  - https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
  - https://v.firebog.net/hosts/static/w3kbl.txt
  - https://v.firebog.net/hosts/AdguardDNS.txt
  - https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Hosts-File.txt
permitted: 
  - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt

blocklist_output: /etc/powerdns/blocklist.lua
permitted_output: /etc/powerdns/permitted.lua
